language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t herbertbintoroe/docker-react -f Dockerfile.dev .

script:
     - docker run -e CI=true herbertbintoroe/docker-react npm run test
